### ISSUE TITLE
Ignore directories

### ISSUE THREAD

**Issue by ghost** [drmargarido/TodoTreeView#1]
Sometimes some tags from my deps show up in my Todo View, which it's really annoying for me, so a table which contains all ignored directories would be great. I don't much of lite, but I guess I can add this feature.

**Comment by drmargarido** [comment]
Yes, that would be a nice improvement. You can filter the files you don't want in the `refresh_cache` function. Tell me if you need any help implementing it.

**Comment by drmargarido** [comment]
How is the progress on this issue?

**Comment by drmargarido** [comment]
Since there is no progress on this issue I will pick it myself and implement the ignoring of directories.

**Comment by drmargarido** [comment]
Implemented with these changes -> f0e61dc80190472262920b51c2078333942fd277
