### ISSUE TITLE
Color style for tags

### ISSUE THREAD

**Issue by itmitica** [drmargarido/TodoTreeView#13]
Great job with the Toggle Focus! Thanks.

Would it be possible to have color style for the tags: TODO red or blue and DONE in faded gray, for example?

**Comment by drmargarido** [comment]
Sure, I can allow colors to be configured per user. Not sure if I will use them in the default setup

**Comment by drmargarido** [comment]
Ok, seems to be working. Still need to check some things but will push it shortly.
![Captura de ecrã de 2024-03-16 09-14-04](https://github.com/drmargarido/TodoTreeView/assets/16456150/dfc12250-a396-4835-b683-903c816e6a85)

**Comment by drmargarido** [comment]
Implementation done and released in commit https://github.com/drmargarido/TodoTreeView/commit/9ca164bb5540fd67058d9cc24fd70d0d9fb54971.
You can check the way to configure the colors in the README

**Comment by itmitica** [comment]
Working as described.

**Comment by itmitica** [comment]
For this code, I'm not seeing the declared colors. Is there something that I'm doing wrong?

```
config.tag_colors["TODO"] = {
  tag={common.color("#ff0000")},
  tag_hover={common.color("#00ff00")},
  text={common.color("#A26769")},
  text_hover={common.color("#6D2E46")},
}
```

![image](https://github.com/drmargarido/TodoTreeView/assets/1570477/d2d09ee7-0052-405b-8531-8ab22c73fa91)

**Comment by drmargarido** [comment]
With the current implementation in this mode it only uses the text color, because the tag and the text are on the same line. For the other mode it uses both because the tag is split from the description.

I will update it to consider all colors in both modes.

**Comment by drmargarido** [comment]
After commit https://github.com/drmargarido/TodoTreeView/commit/228bf64d4cf33a91785197f7e98562e3e7be4ef6 the tag color is also used in the file mode. Also added a new config to allow configuration of the filename color. Check the README for examples.

One extra note, I noticed an error being displayed in the logs of the lite-xl after defining colors for a tag. Updated the README with an example that prevents that, any color not specified will use the current style.text and style.accent colors.

**Comment by itmitica** [comment]
Confirming.

![image](https://github.com/drmargarido/TodoTreeView/assets/1570477/aed61254-6182-4d4e-b213-806592c6100c)

Great job!

**Comment by drmargarido** [comment]
After you have it all configured to your likening, can you send a screenshot? I'm curious with the final result

**Comment by itmitica** [comment]
![image](https://github.com/drmargarido/TodoTreeView/assets/1570477/ed58b130-0b8b-44fa-ae53-63556735e42a)

**Comment by itmitica** [comment]
![image](https://github.com/drmargarido/TodoTreeView/assets/1570477/9a155220-9765-47f5-9527-0f6c2d717646)

![image](https://github.com/drmargarido/TodoTreeView/assets/1570477/5bf8c28f-c7b0-45ac-8f0e-27b1bb2f6e75)

**Comment by drmargarido** [comment]
Those look pretty nice! :+1:

**Comment by itmitica** [comment]
For my current purpose, I think of these TODOs as bookmarks. I also try to follow the TODO-DOING-DONE process in keeping up with the current state of my daily, monthly, annual  or just simply ephemeral tasks.

TodoTreeView is now the single one plugin and Lite-XL is probably the best editor  that has managed not to frustrate me or box me in while trying to follow this process in a simple and straightforward manner.

Thanks.
