### ISSUE TITLE
Filter the TODO entries

### ISSUE THREAD

**Issue by itmitica** [drmargarido/TodoTreeView#14]
How about a way to filter, a way to reduce the TODO tree view, to include only entries based on a particular search string.

**Comment by drmargarido** [comment]
Filtering of the notes implemented in the commit https://github.com/drmargarido/TodoTreeView/commit/df264c0a993c924182bf81feb232ad7b1484de05

**Comment by itmitica** [comment]
Working as intended.

I get warning messages: `Using CommandView:enter in a deprecated way`, `Using deprecated function: CommandView:set_text`.

And I think there should be an info about the TodoTreeView currently being filtered. Something like: "Showing only entries containing:..." or "Filtered by: ..." or simply "List is currently filtered.".

**Comment by drmargarido** [comment]
Released changes with implementation for both things to the most recent master version.

- Implemented the status display of the current filtering in the commit https://github.com/drmargarido/TodoTreeView/commit/d1551fc18837c8a36135bf2c2b9d7863ac0062e3
- Fixed deprecated method usage and updated filter command name in commit https://github.com/drmargarido/TodoTreeView/commit/c7efda5d64bef19482409348942f01fef9a63222

**Comment by itmitica** [comment]
Working great!
