### ISSUE TITLE
Make ' - ' and 'blank' configurable

### ISSUE THREAD

**Issue by itmitica** [drmargarido/TodoTreeView#15]
I think it could be useful to be able to change the separator between tag and text (default ' - ') and the replacement text (default 'blank') for when the tag has no corresponding text.

**Comment by drmargarido** [comment]
Allowed configuration of the separator and the default text for tags without text. https://github.com/drmargarido/TodoTreeView/commit/228bf64d4cf33a91785197f7e98562e3e7be4ef6

**Comment by itmitica** [comment]
Working as intended.

Fantastic!
