### ISSUE TITLE
A third mode: 'filesandtags', to aggregate same tag entries in 'file' mode as well

### ISSUE THREAD

**Issue by itmitica** [drmargarido/TodoTreeView#16]
When mode is 'fileandtags', aggregate same tag entries in each file instead of listing each tag as it occurs in the respective file.

**Comment by drmargarido** [comment]
Yeah, this makes more sense to be an extra mode, the tree of file > tag > todo will have more depth and doesn't really replace the file mode.

**Comment by drmargarido** [comment]
New mode implemented with the name "file_tag" in this commit https://github.com/drmargarido/TodoTreeView/commit/deaeda63fc6af2965aa5b3a6d6a7901806983544.

**Comment by itmitica** [comment]
Working as described. Thanks!

![image](https://github.com/drmargarido/TodoTreeView/assets/1570477/c8f31899-a576-4d66-ae52-c5390f4ba1fa)
