### ISSUE TITLE
command to add to the todotreeview from the current file, which is not in the project folder

### ISSUE THREAD

**Issue by itmitica** [drmargarido/TodoTreeView#17]
Lite has the Ctrl-O command which allows opening file that are outside of the project folder. Any possibility to trigger adding to the TodoTreeView a file like that?

**Comment by drmargarido** [comment]
Implemented with commit https://github.com/drmargarido/TodoTreeView/commit/abd289958694e8860e51c3c42bc35cc8a8e7a4e0.

**Comment by itmitica** [comment]
Thank you!

Sorry for the delayed response. I wanted to make sure and test the feature extensively.

I think it should be implemented as a new feature: current file or current directory.
