### ISSUE TITLE
"current file" or "current directory" discovery modes

### ISSUE THREAD

**Issue by itmitica** [drmargarido/TodoTreeView#18]
At one point, I find it difficult to concentrate in my workflow with so many entries from so many files.

I think a manual discovery mode would help.
First with having zero on-start impact on machine resources: no entries until requested.
Secondly, with narrowing the focus to the entries from a single file, the current opened file. A filter of some sorts, if you want.

Option to set discovery mode to manual or automatic.
Option to trigger discovery when in manual discovery mode.
If no files are being currently edited, manual discovery mode should be "current directory".
If a file is being currently focused, manual discovery mode should be "current file".

**Comment by drmargarido** [comment]
I agree that having a more focused context could be useful, but not sure about some things here. 

1. I don't think it's worth having zero entries at the start and have to manually do things for the entries to appear. With this more interactions from the user are needed and that's not the base behaviour I would want.
2. For the discovery modes, I don't think manual and automatic really mean much here.

With that said, let's organize this a bit better. This seems to be the mixing of two different concepts, the scope of the notes being displayed and the management of the possible scopes.

From what you said we would have the following two scopes:
- all: Picks notes from the current folder, all it's children and individually opened files
- current: Only current file in focus

And two possible scope management policies / workflows:
- default: Always stays in the all scope
- itmitica: Focus on the current scope, goes back to all scope when editing area not in focus or no tabs open

**Comment by drmargarido** [comment]
Thought about two extra possible scopes:

- folder: Would pick notes from the directories files but not from the individually opened files.
- open: Would pick notes from currently opened files (in the tabs) but would not pick anything from the directory files.

**Comment by drmargarido** [comment]
Well, I will setup the 'all' and 'current' scopes and implement the new workflow.

**Comment by drmargarido** [comment]
Implemented in commit https://github.com/drmargarido/TodoTreeView/commit/8f057f18c88546c00f71dede1f178e46e29e00fa. Check the readme for instructions on the new scopes.
Does it handle everything the way you expected?

**Comment by itmitica** [comment]
It does. Great job!
_Sorry about the delayed feedback._
