### ISSUE TITLE
porting to lite-xl

### ISSUE THREAD

**Issue by franko** [drmargarido/TodoTreeView#3]
It would be nice to have an adaptation of this plugin to lite-xl.

There is an issue opened for lite-xl:

https://github.com/franko/lite-xl/issues/164

The adaptations required should be minor, lite-xl introduced a few incompatibilities with the original editor.

**Comment by drmargarido** [comment]
Thanks for the report, I only use base lite so I didn't notice that.
I will test it to see what is the problem with the plugin.

**Comment by franko** [comment]
Thank you @drmargarido, lite-xl is available from:

https://github.com/franko/lite-xl

You can contact me at any moment if you need help of clarifications about the specificities of lite-xl or also about anything else you may need.

**Comment by drmargarido** [comment]
Hey, I made the plugin work in lite-xl but there is still one problem I'm trying to understand.
If I split the view on the left side it can be resized without trouble but when doing that on right right side the main view will disappear when I resize the todoview.

Demo: 
![litexl-todotreeview](https://user-images.githubusercontent.com/16456150/117285730-3ee1a200-ae60-11eb-9f71-25edbd725393.gif)

Looks like the main view is also resizing, and probably using the wrong coordinates as target? Not sure, am I doing something wrong? If you want to look at the code you can check  27d3886c78b408107049c817abae5ff3cd5ec62c .
Around line 328 and the update function are the main points that split the node and make the resize.

**Comment by franko** [comment]
Hey, it was on my side, you found a bug in lite-xl resizing logic for nested nodes.

I fixed that in the master branch:

https://github.com/franko/lite-xl/commit/55a6888818f6658a0c98230c01e99404e96925f2

As the problem was fixed in the lua side, actually inside data/core/rootview.lua you can easily test by installing the latest version of lite-xl, the version 1.16.8, and copying the rootview.lua file that contains the fix.

Otherwise I like very much your plugin, thank you for doing the port to lite-xl!

**Comment by franko** [comment]
I did a new release that includes the fix so no need to tweak you install and other users can try the plugin as well.

**Comment by drmargarido** [comment]
Nice, glad it works now!
Good job on lite-xl, it has some nice improvements.
