### ISSUE TITLE
Throws an error

### ISSUE THREAD

**Issue by Stefanoko** [drmargarido/TodoTreeView#7]
I cannot get it to work. Lite XL version 2.1.1 starts up with a red error bar on top that tells the plugin is not compatible, I should get the newest version.

**Comment by anaCIRdes** [comment]
Also the same on my Lite XL version 2.1.1. Any solutions?

**Comment by drmargarido** [comment]
Thanks for the report, it's fixed in the most recent version with the commit abb0cc5fe7963be6693c8339e548360a1bd53a36

**Comment by drmargarido-lkwd** [comment]
Adding the two comments here to continue with the issue.
- https://github.com/drmargarido/TodoTreeView/commit/abb0cc5fe7963be6693c8339e548360a1bd53a36#commitcomment-99891861
- https://github.com/drmargarido/TodoTreeView/commit/abb0cc5fe7963be6693c8339e548360a1bd53a36#commitcomment-99892507

**Comment by drmargarido** [comment]
Adding the two comments here to continue with the issue.

    https://github.com/drmargarido/TodoTreeView/commit/abb0cc5fe7963be6693c8339e548360a1bd53a36#commitcomment-99891861
    https://github.com/drmargarido/TodoTreeView/commit/abb0cc5fe7963be6693c8339e548360a1bd53a36#commitcomment-99892507

**Comment by drmargarido** [comment]
I compiled the most recent version of lite-xl (2.1.1), copied the todotreeview-xl.lua file to the `share/lite-xl/plugins/` folder and it worked directly. I noticed some slowness in bigger repositories, but it did work after a bit.
Also tested the disabling and enabling of the plugin with closing lite-xl in the middle and it did also work.

I'm using elementary OS 6.1 Jólnir, in which OS are you using?
Also you are on lite-xl version 2.1.1 but did you compile it from source or used another method?

**Comment by Stefanoko** [comment]
Thanks for looking into this, I really appreciate your help.
I am on Win7 x64 and I downloaded Lite-xl as a binary package for Windows, from https://lite-xl.com/en/downloads. 

All other plugins run fine. 
What's interesting, though, all other .lua files in my plugin-folder are between 2 kb and 20 kb, whereas todotreeview-xl.lua weighs in at 332 kb.

**Comment by Stefanoko** [comment]
The huge file size got me thinking. Inside it looked different from the other plugins. So anyway, I copied the code  directly here from Github, then pasted it into the downloaded version, overwriting everything that was in todotreeview-xl.lua. Et voila, now it works. Like a charm.

Thanks a ton for this amazing plugin. Enormously useful, a huge time saver.

**Comment by drmargarido** [comment]
Yeah, that file size seems weird.
Well, nice that it's working now and glad that is useful to you!
