### ISSUE TITLE
Performance Improvements

### ISSUE THREAD

**Issue by jgmdev** [drmargarido/TodoTreeView#8]
Just to let you know I integrated this plugin into [Pragtical Plugins Repo](https://github.com/pragtical/plugins/blob/master/plugins/todotreeview.lua) and made some performance improvements to it so it behaves better with large projects, improvements include:

* No longer subject to max files limit of the editor, it uses its own file iterator.
* Tags are scanned for individual documents on file save instead of re-iterating the entire project tree on each save.
* Monitoring of project directory and mode changes to refresh the list.
* Added settings ui configuration support.
* Removal of file from cache when it is deleted from the editor.
* Added refresh command just in case.

Maybe you would like to integrate some of the changes on this repo, and thanks for this nice plugin!

**Comment by drmargarido** [comment]
Thanks for the head up. Good job with the improvements, I will add some of them later for sure :+1:
