### ISSUE TITLE
Fix todo view box auto-resizing itself after being grabbed

### ISSUE THREAD

**Issue by PerilousBooklet** [drmargarido/TodoTreeView#9]
The TODO tree view box auto-resizes itself to a value of around 50 after being grabbed and extended towards the left.
This happens whenever I toggle on the TODO tree view.

**Comment by drmargarido** [comment]
Thanks for the report!
After some testing I found the issue, it's a bug on lite-xl code. 
Submitted a PR to fix it https://github.com/lite-xl/lite-xl/pull/1657

**Comment by drmargarido** [comment]
The fix to lite-xl was merged today. Update to the most recent version and the issue should be solved.
